<?php
/**
 * Helpers related to the content generated by plugins.
 * - Contact Form 7 Google Tag Manager event
 */

namespace Ricubai\WPHelpers;

/**
 * Class PluginContentHelper
 *
 * @package Ricubai\WPHelpers
 */
class PluginContentHelper {
    public static function cf7_submit_gtag_event( string $send_to ) {
        add_action( 'wp_footer', static function() use ( $send_to ) {
            ?>
            <script>
                document.addEventListener('wpcf7mailsent', function (event) {
                    gtag('event', 'conversion', {
                        'send_to': '<?php echo esc_attr( $send_to ); ?>',
                        'event_category': event.detail.contactFormId,
                        'event_label': event.detail.unitTag
                    });
                }, false);
            </script>
            <?php
        } );
    }

}
